/********************************************************************************
** Form generated from reading UI file 'tradingdialog.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TRADINGDIALOG_H
#define UI_TRADINGDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_tradingDialog
{
public:
    QTabWidget *TradingTabWidget;
    QWidget *OrderBook;
    QTableWidget *BidsTable;
    QTableWidget *AsksTable;
    QLabel *BidsCount;
    QLabel *AsksCount;
    QLabel *XumaSupply;
    QLabel *XumaDemand;
    QLabel *BtcDemand;
    QLabel *BtcSupply;
    QFrame *line;
    QWidget *MarketHistory;
    QTableWidget *MarketHistoryTable;
    QWidget *OpenOrders;
    QTableWidget *OpenOrdersTable;
    QCheckBox *AdvancedView;
    QWidget *TradeHistory;
    QTableWidget *TradeHistoryTable;
    QWidget *BuyTab;
    QPushButton *BuyXuma;
    QLabel *label_3;
    QLineEdit *UnitsInput;
    QLineEdit *BuyBidPriceEdit;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QPushButton *Buy_Max_Amount;
    QComboBox *BuyBidcomboBox;
    QComboBox *buyOrdertypeCombo;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout_3;
    QLabel *label232;
    QLabel *BtcAvailableLbl;
    QLabel *BtcAvailableLbl_2;
    QWidget *layoutWidge2;
    QHBoxLayout *horizontalLayout_4;
    QLabel *label_9;
    QLabel *BuyCostLabel;
    QLabel *label_10;
    QLabel *label_24;
    QWidget *SellTab;
    QLabel *label_16;
    QComboBox *SellBidcomboBox;
    QLabel *label_18;
    QPushButton *Sell_Max_Amount;
    QLabel *label_20;
    QComboBox *SellOrdertypeCombo;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *UnitsInputXuma;
    QLineEdit *SellBidPriceEdit;
    QPushButton *SellXumaBTN;
    QWidget *layoutWidget3;
    QHBoxLayout *horizontalLayout;
    QLabel *label232_2;
    QLabel *XumaAvailableLabel;
    QLabel *labelXuma;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_2;
    QLabel *label_19;
    QLabel *SellCostLabel;
    QLabel *label_17;
    QLabel *label_23;
    QWidget *BalanceTab;
    QLabel *BitcoinBalanceLabel;
    QLabel *XumaBalanceLabel;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *XumaAvailableLabel_2;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *XumaPendingLabel;
    QLabel *label_15;
    QLabel *BitcoinAvailableLabel;
    QLabel *label_31;
    QLabel *BitcoinPendingLabel;
    QLabel *label_33;
    QPushButton *GenDepositBTN;
    QLabel *DepositAddressLabel;
    QLabel *label_8;
    QWidget *widgetConversion;
    QPushButton *btnUpdateMarketData;
    QLabel *lblConvertVCoin;
    QLineEdit *txtConvertVCoinQty;
    QPushButton *btnConvertXuma;
    QLabel *lblConvertVCoinResults;
    QLabel *iconOverviewUpdateWait;
    QWidget *ApiSettings;
    QLabel *bittrex;
    QPushButton *UpdateKeys;
    QLabel *label_2;
    QLineEdit *SecretKeyInput;
    QLineEdit *ApiKeyInput;
    QLabel *label;
    QWidget *widget;
    QLabel *Bid;
    QLabel *Ask;
    QLabel *volumet;
    QLabel *volumebtc;

    void setupUi(QDialog *tradingDialog)
    {
        if (tradingDialog->objectName().isEmpty())
            tradingDialog->setObjectName(QStringLiteral("tradingDialog"));
        tradingDialog->resize(780, 476);
        TradingTabWidget = new QTabWidget(tradingDialog);
        TradingTabWidget->setObjectName(QStringLiteral("TradingTabWidget"));
        TradingTabWidget->setEnabled(true);
        TradingTabWidget->setGeometry(QRect(10, 40, 761, 431));
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        TradingTabWidget->setFont(font);
        TradingTabWidget->setTabPosition(QTabWidget::North);
        OrderBook = new QWidget();
        OrderBook->setObjectName(QStringLiteral("OrderBook"));
        BidsTable = new QTableWidget(OrderBook);
        BidsTable->setObjectName(QStringLiteral("BidsTable"));
        BidsTable->setGeometry(QRect(12, 60, 350, 321));
        QPalette palette;
        QBrush brush(QColor(51, 51, 51, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        QBrush brush1(QColor(85, 85, 85, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        BidsTable->setPalette(palette);
        QFont font1;
        font1.setPointSize(9);
        font1.setBold(false);
        font1.setWeight(50);
        BidsTable->setFont(font1);
        BidsTable->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        AsksTable = new QTableWidget(OrderBook);
        AsksTable->setObjectName(QStringLiteral("AsksTable"));
        AsksTable->setGeometry(QRect(396, 60, 350, 321));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        AsksTable->setPalette(palette1);
        AsksTable->setFont(font1);
        AsksTable->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        BidsCount = new QLabel(OrderBook);
        BidsCount->setObjectName(QStringLiteral("BidsCount"));
        BidsCount->setGeometry(QRect(10, 10, 91, 16));
        AsksCount = new QLabel(OrderBook);
        AsksCount->setObjectName(QStringLiteral("AsksCount"));
        AsksCount->setGeometry(QRect(380, 10, 91, 16));
        XumaSupply = new QLabel(OrderBook);
        XumaSupply->setObjectName(QStringLiteral("XumaSupply"));
        XumaSupply->setGeometry(QRect(540, 10, 180, 15));
        XumaSupply->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        XumaDemand = new QLabel(OrderBook);
        XumaDemand->setObjectName(QStringLiteral("XumaDemand"));
        XumaDemand->setGeometry(QRect(160, 10, 190, 15));
        XumaDemand->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BtcDemand = new QLabel(OrderBook);
        BtcDemand->setObjectName(QStringLiteral("BtcDemand"));
        BtcDemand->setGeometry(QRect(200, 30, 150, 15));
        BtcDemand->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        BtcSupply = new QLabel(OrderBook);
        BtcSupply->setObjectName(QStringLiteral("BtcSupply"));
        BtcSupply->setGeometry(QRect(570, 30, 150, 15));
        BtcSupply->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        line = new QFrame(OrderBook);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(370, 60, 20, 321));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        TradingTabWidget->addTab(OrderBook, QString());
        MarketHistory = new QWidget();
        MarketHistory->setObjectName(QStringLiteral("MarketHistory"));
        MarketHistoryTable = new QTableWidget(MarketHistory);
        MarketHistoryTable->setObjectName(QStringLiteral("MarketHistoryTable"));
        MarketHistoryTable->setGeometry(QRect(10, 10, 740, 371));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        MarketHistoryTable->setPalette(palette2);
        TradingTabWidget->addTab(MarketHistory, QString());
        OpenOrders = new QWidget();
        OpenOrders->setObjectName(QStringLiteral("OpenOrders"));
        OpenOrdersTable = new QTableWidget(OpenOrders);
        OpenOrdersTable->setObjectName(QStringLiteral("OpenOrdersTable"));
        OpenOrdersTable->setGeometry(QRect(10, 40, 740, 341));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        OpenOrdersTable->setPalette(palette3);
        AdvancedView = new QCheckBox(OpenOrders);
        AdvancedView->setObjectName(QStringLiteral("AdvancedView"));
        AdvancedView->setGeometry(QRect(10, 10, 150, 17));
        TradingTabWidget->addTab(OpenOrders, QString());
        TradeHistory = new QWidget();
        TradeHistory->setObjectName(QStringLiteral("TradeHistory"));
        TradeHistoryTable = new QTableWidget(TradeHistory);
        TradeHistoryTable->setObjectName(QStringLiteral("TradeHistoryTable"));
        TradeHistoryTable->setGeometry(QRect(0, 10, 751, 361));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        TradeHistoryTable->setPalette(palette4);
        TradingTabWidget->addTab(TradeHistory, QString());
        BuyTab = new QWidget();
        BuyTab->setObjectName(QStringLiteral("BuyTab"));
        BuyXuma = new QPushButton(BuyTab);
        BuyXuma->setObjectName(QStringLiteral("BuyXuma"));
        BuyXuma->setGeometry(QRect(30, 330, 131, 23));
        QIcon icon;
        icon.addFile(QStringLiteral(":/icons/bitcoin"), QSize(), QIcon::Normal, QIcon::Off);
        BuyXuma->setIcon(icon);
        label_3 = new QLabel(BuyTab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 110, 46, 23));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        label_3->setFont(font2);
        UnitsInput = new QLineEdit(BuyTab);
        UnitsInput->setObjectName(QStringLiteral("UnitsInput"));
        UnitsInput->setGeometry(QRect(310, 110, 441, 23));
        QFont font3;
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        UnitsInput->setFont(font3);
        BuyBidPriceEdit = new QLineEdit(BuyTab);
        BuyBidPriceEdit->setObjectName(QStringLiteral("BuyBidPriceEdit"));
        BuyBidPriceEdit->setGeometry(QRect(310, 140, 441, 23));
        BuyBidPriceEdit->setFont(font3);
        label_4 = new QLabel(BuyTab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(780, 110, 31, 23));
        label_5 = new QLabel(BuyTab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(780, 140, 31, 23));
        label_6 = new QLabel(BuyTab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 140, 46, 23));
        label_6->setFont(font2);
        label_7 = new QLabel(BuyTab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 170, 91, 16));
        label_7->setFont(font2);
        Buy_Max_Amount = new QPushButton(BuyTab);
        Buy_Max_Amount->setObjectName(QStringLiteral("Buy_Max_Amount"));
        Buy_Max_Amount->setGeometry(QRect(110, 110, 191, 23));
        QFont font4;
        font4.setPointSize(10);
        Buy_Max_Amount->setFont(font4);
        BuyBidcomboBox = new QComboBox(BuyTab);
        BuyBidcomboBox->setObjectName(QStringLiteral("BuyBidcomboBox"));
        BuyBidcomboBox->setGeometry(QRect(110, 140, 191, 23));
        BuyBidcomboBox->setFont(font4);
        buyOrdertypeCombo = new QComboBox(BuyTab);
        buyOrdertypeCombo->setObjectName(QStringLiteral("buyOrdertypeCombo"));
        buyOrdertypeCombo->setGeometry(QRect(110, 170, 191, 23));
        buyOrdertypeCombo->setFont(font4);
        layoutWidget1 = new QWidget(BuyTab);
        layoutWidget1->setObjectName(QStringLiteral("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(21, 11, 227, 19));
        horizontalLayout_3 = new QHBoxLayout(layoutWidget1);
        horizontalLayout_3->setObjectName(QStringLiteral("horizontalLayout_3"));
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        label232 = new QLabel(layoutWidget1);
        label232->setObjectName(QStringLiteral("label232"));
        label232->setFont(font2);

        horizontalLayout_3->addWidget(label232);

        BtcAvailableLbl = new QLabel(layoutWidget1);
        BtcAvailableLbl->setObjectName(QStringLiteral("BtcAvailableLbl"));
        QPalette palette5;
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush3(QColor(0, 170, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush3);
        QBrush brush4(QColor(0, 255, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush4);
        QBrush brush5(QColor(0, 212, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        QBrush brush6(QColor(0, 85, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush6);
        QBrush brush7(QColor(0, 113, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush3);
        QBrush brush8(QColor(255, 255, 255, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        QBrush brush9(QColor(127, 212, 127, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        QBrush brush10(QColor(255, 255, 220, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        BtcAvailableLbl->setPalette(palette5);
        BtcAvailableLbl->setFont(font2);
        BtcAvailableLbl->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard|Qt::TextSelectableByMouse);

        horizontalLayout_3->addWidget(BtcAvailableLbl);

        BtcAvailableLbl_2 = new QLabel(layoutWidget1);
        BtcAvailableLbl_2->setObjectName(QStringLiteral("BtcAvailableLbl_2"));
        BtcAvailableLbl_2->setFont(font2);

        horizontalLayout_3->addWidget(BtcAvailableLbl_2);

        layoutWidge2 = new QWidget(BuyTab);
        layoutWidge2->setObjectName(QStringLiteral("layoutWidge2"));
        layoutWidge2->setGeometry(QRect(11, 301, 259, 19));
        horizontalLayout_4 = new QHBoxLayout(layoutWidge2);
        horizontalLayout_4->setObjectName(QStringLiteral("horizontalLayout_4"));
        horizontalLayout_4->setContentsMargins(0, 0, 0, 0);
        label_9 = new QLabel(layoutWidge2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setFont(font2);

        horizontalLayout_4->addWidget(label_9);

        BuyCostLabel = new QLabel(layoutWidge2);
        BuyCostLabel->setObjectName(QStringLiteral("BuyCostLabel"));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        BuyCostLabel->setPalette(palette6);
        BuyCostLabel->setFont(font2);
        BuyCostLabel->setAutoFillBackground(false);
        BuyCostLabel->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByMouse);

        horizontalLayout_4->addWidget(BuyCostLabel);

        label_10 = new QLabel(layoutWidge2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setFont(font);

        horizontalLayout_4->addWidget(label_10);

        label_24 = new QLabel(BuyTab);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(460, 300, 281, 81));
        label_24->setPixmap(QPixmap(QString::fromUtf8(":/images/bittrex")));
        TradingTabWidget->addTab(BuyTab, QString());
        SellTab = new QWidget();
        SellTab->setObjectName(QStringLiteral("SellTab"));
        label_16 = new QLabel(SellTab);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(780, 140, 31, 23));
        SellBidcomboBox = new QComboBox(SellTab);
        SellBidcomboBox->setObjectName(QStringLiteral("SellBidcomboBox"));
        SellBidcomboBox->setGeometry(QRect(110, 140, 191, 23));
        SellBidcomboBox->setFont(font4);
        label_18 = new QLabel(SellTab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 110, 46, 23));
        label_18->setFont(font2);
        Sell_Max_Amount = new QPushButton(SellTab);
        Sell_Max_Amount->setObjectName(QStringLiteral("Sell_Max_Amount"));
        Sell_Max_Amount->setGeometry(QRect(110, 110, 191, 23));
        Sell_Max_Amount->setFont(font4);
        label_20 = new QLabel(SellTab);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 170, 91, 16));
        label_20->setFont(font2);
        SellOrdertypeCombo = new QComboBox(SellTab);
        SellOrdertypeCombo->setObjectName(QStringLiteral("SellOrdertypeCombo"));
        SellOrdertypeCombo->setGeometry(QRect(110, 170, 191, 23));
        SellOrdertypeCombo->setFont(font4);
        label_21 = new QLabel(SellTab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 140, 46, 23));
        label_21->setFont(font2);
        label_22 = new QLabel(SellTab);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(780, 110, 31, 23));
        UnitsInputXuma = new QLineEdit(SellTab);
        UnitsInputXuma->setObjectName(QStringLiteral("UnitsInputXuma"));
        UnitsInputXuma->setGeometry(QRect(310, 110, 441, 23));
        UnitsInputXuma->setFont(font3);
        SellBidPriceEdit = new QLineEdit(SellTab);
        SellBidPriceEdit->setObjectName(QStringLiteral("SellBidPriceEdit"));
        SellBidPriceEdit->setGeometry(QRect(310, 140, 441, 23));
        SellBidPriceEdit->setFont(font3);
        SellXumaBTN = new QPushButton(SellTab);
        SellXumaBTN->setObjectName(QStringLiteral("SellXumaBTN"));
        SellXumaBTN->setGeometry(QRect(30, 330, 131, 23));
        SellXumaBTN->setIcon(icon);
        layoutWidget3 = new QWidget(SellTab);
        layoutWidget3->setObjectName(QStringLiteral("layoutWidget3"));
        layoutWidget3->setGeometry(QRect(22, 12, 258, 19));
        horizontalLayout = new QHBoxLayout(layoutWidget3);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        label232_2 = new QLabel(layoutWidget3);
        label232_2->setObjectName(QStringLiteral("label232_2"));
        label232_2->setFont(font2);

        horizontalLayout->addWidget(label232_2);

        XumaAvailableLabel = new QLabel(layoutWidget3);
        XumaAvailableLabel->setObjectName(QStringLiteral("XumaAvailableLabel"));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush8);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        XumaAvailableLabel->setPalette(palette7);
        XumaAvailableLabel->setFont(font2);
        XumaAvailableLabel->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard|Qt::TextSelectableByMouse);

        horizontalLayout->addWidget(XumaAvailableLabel);

        labelXuma = new QLabel(layoutWidget3);
        labelXuma->setObjectName(QStringLiteral("labelXuma"));
        labelXuma->setFont(font2);

        horizontalLayout->addWidget(labelXuma);

        layoutWidget = new QWidget(SellTab);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 300, 268, 19));
        horizontalLayout_2 = new QHBoxLayout(layoutWidget);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        label_19 = new QLabel(layoutWidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setFont(font2);

        horizontalLayout_2->addWidget(label_19);

        SellCostLabel = new QLabel(layoutWidget);
        SellCostLabel->setObjectName(QStringLiteral("SellCostLabel"));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush7);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush8);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush7);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        SellCostLabel->setPalette(palette8);
        SellCostLabel->setFont(font2);
        SellCostLabel->setAutoFillBackground(false);
        SellCostLabel->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByMouse);

        horizontalLayout_2->addWidget(SellCostLabel);

        label_17 = new QLabel(layoutWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setFont(font);

        horizontalLayout_2->addWidget(label_17);

        label_23 = new QLabel(SellTab);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(460, 300, 281, 81));
        label_23->setPixmap(QPixmap(QString::fromUtf8(":/images/bittrex")));
        TradingTabWidget->addTab(SellTab, QString());
        BalanceTab = new QWidget();
        BalanceTab->setObjectName(QStringLiteral("BalanceTab"));
        BitcoinBalanceLabel = new QLabel(BalanceTab);
        BitcoinBalanceLabel->setObjectName(QStringLiteral("BitcoinBalanceLabel"));
        BitcoinBalanceLabel->setGeometry(QRect(470, 30, 150, 16));
        XumaBalanceLabel = new QLabel(BalanceTab);
        XumaBalanceLabel->setObjectName(QStringLiteral("XumaBalanceLabel"));
        XumaBalanceLabel->setGeometry(QRect(150, 30, 150, 16));
        label_11 = new QLabel(BalanceTab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 30, 101, 16));
        label_11->setFont(font2);
        label_12 = new QLabel(BalanceTab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(320, 30, 101, 16));
        label_12->setFont(font2);
        XumaAvailableLabel_2 = new QLabel(BalanceTab);
        XumaAvailableLabel_2->setObjectName(QStringLiteral("XumaAvailableLabel_2"));
        XumaAvailableLabel_2->setGeometry(QRect(150, 70, 150, 16));
        label_13 = new QLabel(BalanceTab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 70, 111, 16));
        label_13->setFont(font2);
        label_14 = new QLabel(BalanceTab);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 110, 101, 16));
        label_14->setFont(font2);
        XumaPendingLabel = new QLabel(BalanceTab);
        XumaPendingLabel->setObjectName(QStringLiteral("XumaPendingLabel"));
        XumaPendingLabel->setGeometry(QRect(150, 110, 150, 16));
        label_15 = new QLabel(BalanceTab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(320, 70, 111, 16));
        label_15->setFont(font2);
        BitcoinAvailableLabel = new QLabel(BalanceTab);
        BitcoinAvailableLabel->setObjectName(QStringLiteral("BitcoinAvailableLabel"));
        BitcoinAvailableLabel->setGeometry(QRect(470, 70, 150, 16));
        label_31 = new QLabel(BalanceTab);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(320, 110, 111, 16));
        label_31->setFont(font2);
        BitcoinPendingLabel = new QLabel(BalanceTab);
        BitcoinPendingLabel->setObjectName(QStringLiteral("BitcoinPendingLabel"));
        BitcoinPendingLabel->setGeometry(QRect(470, 110, 150, 16));
        label_33 = new QLabel(BalanceTab);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(30, 200, 221, 16));
        label_33->setFont(font2);
        GenDepositBTN = new QPushButton(BalanceTab);
        GenDepositBTN->setObjectName(QStringLiteral("GenDepositBTN"));
        GenDepositBTN->setGeometry(QRect(30, 160, 411, 23));
        GenDepositBTN->setIcon(icon);
        DepositAddressLabel = new QLabel(BalanceTab);
        DepositAddressLabel->setObjectName(QStringLiteral("DepositAddressLabel"));
        DepositAddressLabel->setGeometry(QRect(200, 200, 261, 16));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush11(QColor(0, 0, 255, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush11);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush11);
        QBrush brush12(QColor(120, 120, 120, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        DepositAddressLabel->setPalette(palette9);
        DepositAddressLabel->setFont(font2);
        DepositAddressLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        DepositAddressLabel->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard|Qt::TextSelectableByMouse);
        label_8 = new QLabel(BalanceTab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(460, 300, 281, 81));
        label_8->setPixmap(QPixmap(QString::fromUtf8(":/images/bittrex")));
        widgetConversion = new QWidget(BalanceTab);
        widgetConversion->setObjectName(QStringLiteral("widgetConversion"));
        widgetConversion->setGeometry(QRect(0, 250, 751, 43));
        widgetConversion->setMinimumSize(QSize(0, 43));
        widgetConversion->setStyleSheet(QStringLiteral(""));
        btnUpdateMarketData = new QPushButton(widgetConversion);
        btnUpdateMarketData->setObjectName(QStringLiteral("btnUpdateMarketData"));
        btnUpdateMarketData->setGeometry(QRect(575, 0, 111, 41));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btnUpdateMarketData->sizePolicy().hasHeightForWidth());
        btnUpdateMarketData->setSizePolicy(sizePolicy);
        QFont font5;
        font5.setFamily(QStringLiteral("calibri"));
        font5.setBold(true);
        font5.setItalic(true);
        font5.setWeight(75);
        btnUpdateMarketData->setFont(font5);
        btnUpdateMarketData->setStyleSheet(QStringLiteral("margin:0px;text-align:center;padding:2px;border-radius:3px;font-style:italic;width:100px;font-size:14px;font-family:calibri;font-weight:600;"));
        btnUpdateMarketData->setIconSize(QSize(150, 35));
        btnUpdateMarketData->setAutoDefault(true);
        lblConvertVCoin = new QLabel(widgetConversion);
        lblConvertVCoin->setObjectName(QStringLiteral("lblConvertVCoin"));
        lblConvertVCoin->setGeometry(QRect(30, 10, 131, 20));
        lblConvertVCoin->setStyleSheet(QStringLiteral(""));
        txtConvertVCoinQty = new QLineEdit(widgetConversion);
        txtConvertVCoinQty->setObjectName(QStringLiteral("txtConvertVCoinQty"));
        txtConvertVCoinQty->setGeometry(QRect(160, 10, 100, 23));
        txtConvertVCoinQty->setMinimumSize(QSize(100, 23));
        txtConvertVCoinQty->setMaximumSize(QSize(100, 16777215));
        txtConvertVCoinQty->setStyleSheet(QStringLiteral("border: 1px solid #61696c;margin-left:4px;"));
        btnConvertXuma = new QPushButton(widgetConversion);
        btnConvertXuma->setObjectName(QStringLiteral("btnConvertXuma"));
        btnConvertXuma->setGeometry(QRect(260, 10, 51, 23));
        btnConvertXuma->setMinimumSize(QSize(0, 23));
        btnConvertXuma->setStyleSheet(QStringLiteral("border:1px solid #61696c;background:white;font-weight:600;"));
        lblConvertVCoinResults = new QLabel(widgetConversion);
        lblConvertVCoinResults->setObjectName(QStringLiteral("lblConvertVCoinResults"));
        lblConvertVCoinResults->setGeometry(QRect(330, 0, 201, 41));
        lblConvertVCoinResults->setStyleSheet(QStringLiteral(""));
        iconOverviewUpdateWait = new QLabel(widgetConversion);
        iconOverviewUpdateWait->setObjectName(QStringLiteral("iconOverviewUpdateWait"));
        iconOverviewUpdateWait->setGeometry(QRect(670, 10, 24, 24));
        iconOverviewUpdateWait->setPixmap(QPixmap(QString::fromUtf8(":/icons/transaction_1")));
        iconOverviewUpdateWait->setScaledContents(true);
        iconOverviewUpdateWait->setAlignment(Qt::AlignCenter);
        TradingTabWidget->addTab(BalanceTab, QString());
        ApiSettings = new QWidget();
        ApiSettings->setObjectName(QStringLiteral("ApiSettings"));
        bittrex = new QLabel(ApiSettings);
        bittrex->setObjectName(QStringLiteral("bittrex"));
        bittrex->setGeometry(QRect(460, 300, 281, 81));
        bittrex->setStyleSheet(QStringLiteral("opacity:0.4"));
        bittrex->setPixmap(QPixmap(QString::fromUtf8(":/images/bittrex")));
        UpdateKeys = new QPushButton(ApiSettings);
        UpdateKeys->setObjectName(QStringLiteral("UpdateKeys"));
        UpdateKeys->setGeometry(QRect(460, 140, 201, 23));
        UpdateKeys->setIcon(icon);
        label_2 = new QLabel(ApiSettings);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(50, 60, 81, 20));
        label_2->setFont(font2);
        SecretKeyInput = new QLineEdit(ApiSettings);
        SecretKeyInput->setObjectName(QStringLiteral("SecretKeyInput"));
        SecretKeyInput->setGeometry(QRect(160, 100, 501, 23));
        ApiKeyInput = new QLineEdit(ApiSettings);
        ApiKeyInput->setObjectName(QStringLiteral("ApiKeyInput"));
        ApiKeyInput->setGeometry(QRect(160, 60, 501, 23));
        label = new QLabel(ApiSettings);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(50, 100, 91, 20));
        label->setFont(font2);
        TradingTabWidget->addTab(ApiSettings, QString());
        widget = new QWidget(tradingDialog);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(10, 0, 761, 34));
        Bid = new QLabel(widget);
        Bid->setObjectName(QStringLiteral("Bid"));
        Bid->setGeometry(QRect(0, 0, 240, 16));
        Bid->setMinimumSize(QSize(140, 0));
        Ask = new QLabel(widget);
        Ask->setObjectName(QStringLiteral("Ask"));
        Ask->setGeometry(QRect(0, 20, 240, 16));
        Ask->setMinimumSize(QSize(160, 0));
        volumet = new QLabel(widget);
        volumet->setObjectName(QStringLiteral("volumet"));
        volumet->setGeometry(QRect(380, 20, 240, 16));
        volumet->setMinimumSize(QSize(201, 0));
        volumebtc = new QLabel(widget);
        volumebtc->setObjectName(QStringLiteral("volumebtc"));
        volumebtc->setGeometry(QRect(380, 0, 240, 16));
        volumebtc->setMinimumSize(QSize(160, 0));

        retranslateUi(tradingDialog);

        TradingTabWidget->setCurrentIndex(0);
        btnUpdateMarketData->setDefault(true);


        QMetaObject::connectSlotsByName(tradingDialog);
    } // setupUi

    void retranslateUi(QDialog *tradingDialog)
    {
        tradingDialog->setWindowTitle(QApplication::translate("tradingDialog", "Bittrex API", 0));
        BidsCount->setText(QApplication::translate("tradingDialog", "Bids", 0));
        AsksCount->setText(QApplication::translate("tradingDialog", "Asks", 0));
        XumaSupply->setText(QApplication::translate("tradingDialog", "label", 0));
        XumaDemand->setText(QApplication::translate("tradingDialog", "label", 0));
        BtcDemand->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        BtcSupply->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(OrderBook), QApplication::translate("tradingDialog", "Order Book", 0));
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(MarketHistory), QApplication::translate("tradingDialog", "Market History", 0));
        AdvancedView->setText(QApplication::translate("tradingDialog", "Advanced View", 0));
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(OpenOrders), QApplication::translate("tradingDialog", "Open Orders", 0));
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(TradeHistory), QApplication::translate("tradingDialog", "Trade history", 0));
        BuyXuma->setText(QApplication::translate("tradingDialog", "Buy Xuma", 0));
        label_3->setText(QApplication::translate("tradingDialog", "Units", 0));
        label_4->setText(QApplication::translate("tradingDialog", "Xuma", 0));
        label_5->setText(QApplication::translate("tradingDialog", "BTC", 0));
        label_6->setText(QApplication::translate("tradingDialog", "Bid", 0));
        label_7->setText(QApplication::translate("tradingDialog", "Order Type", 0));
        Buy_Max_Amount->setText(QApplication::translate("tradingDialog", "Max", 0));
        label232->setText(QApplication::translate("tradingDialog", "BTC Available:", 0));
        BtcAvailableLbl->setText(QApplication::translate("tradingDialog", "0.00000000", 0));
        BtcAvailableLbl_2->setText(QApplication::translate("tradingDialog", "BTC", 0));
        label_9->setText(QApplication::translate("tradingDialog", "Total w/ 0.25% Fee", 0));
        BuyCostLabel->setText(QApplication::translate("tradingDialog", "0.00000000", 0));
        label_10->setText(QApplication::translate("tradingDialog", "BTC", 0));
        label_24->setText(QString());
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(BuyTab), QApplication::translate("tradingDialog", "Buy", 0));
        label_16->setText(QApplication::translate("tradingDialog", "BTC", 0));
        label_18->setText(QApplication::translate("tradingDialog", "Units", 0));
        Sell_Max_Amount->setText(QApplication::translate("tradingDialog", "Max", 0));
        label_20->setText(QApplication::translate("tradingDialog", "Order Type", 0));
        label_21->setText(QApplication::translate("tradingDialog", "Bid", 0));
        label_22->setText(QApplication::translate("tradingDialog", "Xuma", 0));
        SellXumaBTN->setText(QApplication::translate("tradingDialog", "Sell Xuma", 0));
        label232_2->setText(QApplication::translate("tradingDialog", "Xuma Available:", 0));
        XumaAvailableLabel->setText(QApplication::translate("tradingDialog", " 0.00000000 ", 0));
        labelXuma->setText(QApplication::translate("tradingDialog", "Xuma", 0));
        label_19->setText(QApplication::translate("tradingDialog", "Total w/ 0.25% Fee ", 0));
        SellCostLabel->setText(QApplication::translate("tradingDialog", " 0.00000000", 0));
        label_17->setText(QApplication::translate("tradingDialog", " BTC", 0));
        label_23->setText(QString());
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(SellTab), QApplication::translate("tradingDialog", "Sell", 0));
        BitcoinBalanceLabel->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        XumaBalanceLabel->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        label_11->setText(QApplication::translate("tradingDialog", "Xuma Balance:", 0));
        label_12->setText(QApplication::translate("tradingDialog", "BTC Balance:", 0));
        XumaAvailableLabel_2->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        label_13->setText(QApplication::translate("tradingDialog", "Xuma Available:", 0));
        label_14->setText(QApplication::translate("tradingDialog", "Xuma Pending:", 0));
        XumaPendingLabel->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        label_15->setText(QApplication::translate("tradingDialog", "BTC Available:", 0));
        BitcoinAvailableLabel->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        label_31->setText(QApplication::translate("tradingDialog", "BTC Pending:", 0));
        BitcoinPendingLabel->setText(QApplication::translate("tradingDialog", "TextLabel", 0));
        label_33->setText(QApplication::translate("tradingDialog", "Bittrex Xuma Deposit Address:", 0));
        GenDepositBTN->setText(QApplication::translate("tradingDialog", "Generate Xuma Deposit Address", 0));
        DepositAddressLabel->setText(QString());
        label_8->setText(QString());
        btnUpdateMarketData->setText(QApplication::translate("tradingDialog", "Update", 0));
        lblConvertVCoin->setText(QApplication::translate("tradingDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Convert VCoin:</span></p></body></html>", 0));
        btnConvertXuma->setText(QApplication::translate("tradingDialog", "=", 0));
        lblConvertVCoinResults->setText(QApplication::translate("tradingDialog", "$0.0000 / B0.00000000", 0));
        iconOverviewUpdateWait->setText(QString());
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(BalanceTab), QApplication::translate("tradingDialog", "Balance", 0));
        bittrex->setText(QString());
        UpdateKeys->setText(QApplication::translate("tradingDialog", "Update API Keys", 0));
        label_2->setText(QApplication::translate("tradingDialog", "API Key", 0));
        ApiKeyInput->setText(QString());
        label->setText(QApplication::translate("tradingDialog", "Secret Key", 0));
        TradingTabWidget->setTabText(TradingTabWidget->indexOf(ApiSettings), QApplication::translate("tradingDialog", "Settings", 0));
        Bid->setText(QApplication::translate("tradingDialog", "0.00000000", 0));
        Ask->setText(QApplication::translate("tradingDialog", "0.00000000", 0));
        volumet->setText(QApplication::translate("tradingDialog", "0.000000000", 0));
        volumebtc->setText(QApplication::translate("tradingDialog", "0.00000000", 0));
    } // retranslateUi

};

namespace Ui {
    class tradingDialog: public Ui_tradingDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TRADINGDIALOG_H
